name: Basic example
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  basic-example:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Renovate
        uses: ./
